-- MySQL Script generated by MySQL Workbench
-- Tue Apr 23 12:03:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fsj_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fsj_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fsj_database` DEFAULT CHARACTER SET utf8 ;
USE `fsj_database` ;

-- -----------------------------------------------------
-- Table `fsj_database`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fsj_database`.`user_role` (
  `id_user_role` INT NOT NULL AUTO_INCREMENT,
  `ur_postion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user_role`))
ENGINE = InnoDB;
INSERT INTO `fsj_database`.`user_role` (`ur_postion`) VALUES ('房地产开发商');
INSERT INTO `fsj_database`.`user_role` (`ur_postion`) VALUES ('建筑设计师');
INSERT INTO `fsj_database`.`user_role` (`ur_postion`) VALUES ('建材供应商');

-- -----------------------------------------------------
-- Table `fsj_database`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fsj_database`.`users` (
  `id_user` VARCHAR(11) NOT NULL COMMENT '使用手机号作为主键',
  `us_name` VARCHAR(45) NULL,
  `us_sex` VARCHAR(3) NULL,
  `us_touxiang_url` VARCHAR(100) NULL,
  `user_role_id_user_role` INT NOT NULL,
  `us_password` VARCHAR(26) NOT NULL,
  `us_email` VARCHAR(45) NULL,
  `us_wechat_no` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_users_user_role_idx` (`user_role_id_user_role` ASC),
  CONSTRAINT `fk_users_user_role`
    FOREIGN KEY (`user_role_id_user_role`)
    REFERENCES `fsj_database`.`user_role` (`id_user_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fsj_database`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fsj_database`.`company` (
  `id_company` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(45) NULL,
  `company_address` VARCHAR(45) NULL,
  `date_start` DATETIME NOT NULL,
  `date_end` DATETIME NULL,
  `company_fox` VARCHAR(13) NULL,
  `certificate` VARCHAR(45) NULL,
  `users_id_user` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id_company`),
  INDEX `fk_company_users1_idx` (`users_id_user` ASC),
  CONSTRAINT `fk_company_users1`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `fsj_database`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fsj_database`.`ds_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fsj_database`.`ds_product` (
  `id_ds_product` INT NOT NULL AUTO_INCREMENT,
  `dp_headline` VARCHAR(45) NULL,
  `dp_description` VARCHAR(200) NULL,
  `dp_picture_url` VARCHAR(100) NULL,
  `users_id_user` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id_ds_product`),
  INDEX `fk_ds_product_users1_idx` (`users_id_user` ASC),
  CONSTRAINT `fk_ds_product_users1`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `fsj_database`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fsj_database`.`estate_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fsj_database`.`estate_project` (
  `id_estate_project` INT NOT NULL AUTO_INCREMENT,
  `ep_name` VARCHAR(45) NOT NULL,
  `ep_description` VARCHAR(300) NULL,
  `ep_pdf_url` VARCHAR(100) NULL,
  `ep_time` DATETIME NULL,
  `users_id_user` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id_estate_project`),
  INDEX `fk_estate_project_users1_idx` (`users_id_user` ASC),
  CONSTRAINT `fk_estate_project_users1`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `fsj_database`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fsj_database`.`ranks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fsj_database`.`ranks` (
  `id_rank` INT NOT NULL AUTO_INCREMENT,
  `ranked` FLOAT NULL,
  `users_id_user` VARCHAR(11) NOT NULL,
  `answer_weight` INT NULL,
  `comfirm_weight` TINYINT NULL,
  PRIMARY KEY (`id_rank`),
  INDEX `fk_rank_users1_idx` (`users_id_user` ASC),
  CONSTRAINT `fk_rank_users1`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `fsj_database`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fsj_database`.`estate_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fsj_database`.`estate_answer` (
  `id_estate_answer` INT NOT NULL AUTO_INCREMENT,
  `repeat_time` DATETIME NULL,
  `estate_project_id_estate_project` INT NOT NULL,
  `users_id_designer` VARCHAR(11) NOT NULL,
  `ea_report` TINYINT NULL COMMENT '评分1-5',
  `ea_accepted` TINYINT NOT NULL DEFAULT 0 COMMENT '是否被提问者采纳',
  `ea_draft_url` VARCHAR(100) NULL,
  PRIMARY KEY (`id_estate_answer`),
  INDEX `fk_estate_answer_estate_project1_idx` (`estate_project_id_estate_project` ASC),
  INDEX `fk_estate_answer_users1_idx` (`users_id_designer` ASC),
  CONSTRAINT `fk_estate_answer_estate_project1`
    FOREIGN KEY (`estate_project_id_estate_project`)
    REFERENCES `fsj_database`.`estate_project` (`id_estate_project`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estate_answer_users1`
    FOREIGN KEY (`users_id_designer`)
    REFERENCES `fsj_database`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fsj_database`.`ds_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fsj_database`.`ds_tag` (
  `id_ds_tag` INT NOT NULL AUTO_INCREMENT,
  `tag_name` VARCHAR(45) NOT NULL,
  `users_id_user` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id_ds_tag`),
  INDEX `fk_ds_tag_users1_idx` (`users_id_user` ASC),
  CONSTRAINT `fk_ds_tag_users1`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `fsj_database`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fsj_database`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fsj_database`.`material` (
  `id_material` INT NOT NULL AUTO_INCREMENT,
  `material_name` VARCHAR(45) NULL,
  `material_price` DOUBLE NULL,
  `material_unit` VARCHAR(45) NULL COMMENT '材料单位',
  `material_pic_url` VARCHAR(100) NULL,
  `company_id_company` INT NOT NULL,
  PRIMARY KEY (`id_material`),
  INDEX `fk_material_company1_idx` (`company_id_company` ASC),
  CONSTRAINT `fk_material_company1`
    FOREIGN KEY (`company_id_company`)
    REFERENCES `fsj_database`.`company` (`id_company`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `fsj_database` ;

-- -----------------------------------------------------
-- Placeholder table for view `fsj_database`.`company_material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fsj_database`.`company_material` (`id_material` INT, `material_name` INT, `material_price` INT, `material_unit` INT, `material_pic_url` INT, `id_company` INT, `company_name` INT, `company_address` INT, `date_start` INT, `date_end` INT, `users_id_user` INT, `company_fox` INT);

-- -----------------------------------------------------
-- Placeholder table for view `fsj_database`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fsj_database`.`tag` (`tag_name` INT, `num` INT);

-- -----------------------------------------------------
-- Placeholder table for view `fsj_database`.`designer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fsj_database`.`designer` (`id_user` INT, `us_name` INT, `us_touxiang_url` INT, `ranked` INT);

-- -----------------------------------------------------
-- View `fsj_database`.`company_material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fsj_database`.`company_material`;
USE `fsj_database`;
CREATE  OR REPLACE VIEW `company_material` AS
Select  M.id_material, M.material_name, M.material_price, M.material_unit, material_pic_url, C.id_company,
C.company_name, C.company_address,C.date_start, C.date_end,C.users_id_user,C.company_fox
From company AS C join material  AS M on  C.id_company = M.company_id_company;

-- -----------------------------------------------------
-- View `fsj_database`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fsj_database`.`tag`;
USE `fsj_database`;
CREATE  OR REPLACE VIEW `tag` AS
select  distinct tag_name  ,count(tag_name) as num from ds_tag
group by tag_name
order by num desc;

-- -----------------------------------------------------
-- View `fsj_database`.`designer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fsj_database`.`designer`;
USE `fsj_database`;
CREATE  OR REPLACE VIEW `designer` AS
select U.id_user , U.us_name,U.us_touxiang_url, R.ranked
from (users AS U) inner join (ranks AS R) on U.id_user = R.users_id_user
order by ranked desc;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
